---
sidebar: sidebar 
permalink: reference-new.html 
keywords: new features, release notes, enhancements 
summary: Cloud Volumes ONTAP 9.10.0 には、いくつかの新機能と機能拡張が含まれています。 
---
= Cloud Volumes ONTAP 9.10.0 の新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.10.0 には、いくつかの新機能と機能拡張が含まれています。

その他の機能と拡張機能も、最新バージョンのBlueXPで導入されました。を参照してください https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["BlueXPリリースノート"^] を参照してください。



== 9.10.0 GA （ 2021 年 10 月 4 日）

9.10.0 GA リリースは、 AWS 、 Azure 、 Google Cloud で利用できます。このリリースには、次の新機能と機能拡張が含まれています。



=== 書き込みパフォーマンスの向上

高速の書き込み速度を有効にすると、 Cloud Volumes ONTAP の書き込みパフォーマンスが向上しました。



=== Azure における NVRAM ディスクサイズの増加

Azure の新しい Cloud Volumes ONTAP システムでは、 NVRAM ディスクサイズが 128GiB から 512GiB に拡張されました。


NOTE: シングルノードシステムを選択し、仮想マシンで Ultra SSD がサポートされている場合、システムは 512GiB Premium SSD ではなく 32GiB Ultra SSD を NVRAM に使用します。



== 必要なBlueXPコネクタのバージョン

新しいCloud Volumes ONTAP 9.10.0システムを導入し、既存のシステムを9.10.0にアップグレードするには、BlueXP Connectorがバージョン3.9.11以降を実行している必要があります。



== アップグレードに関する注意事項

* Cloud Volumes ONTAP のアップグレードは、BlueXPから完了している必要があります。System Manager または CLI を使用して Cloud Volumes ONTAP をアップグレードしないでください。これを行うと、システムの安定性に影響を与える可能性
* 9.9.1 リリースから Cloud Volumes ONTAP 9.10.0 にアップグレードできます。BlueXPでは、既存のCloud Volumes ONTAP 9.9.1システムを9.10.0リリースにアップグレードするように求められます。
+
http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["BlueXPから通知があった場合のアップグレード方法について説明します"^]。

* シングルノードシステムのアップグレードでは、 I/O が中断されるまで最大 25 分間システムがオフラインになります。
* HA ペアのアップグレードは無停止で、 I/O が中断されません。無停止アップグレードでは、各ノードが連携してアップグレードされ、クライアントへの I/O の提供が継続されます。
* AWSでは、新しいCloud Volumes ONTAP環境でc4、m4、およびr4 EC2インスタンスタイプはサポートされなくなりました。C4、M4、またはR4インスタンスタイプで実行されている既存のシステムがある場合は、C5、m5、またはr5インスタンスファミリーでインスタンスタイプに変更する必要があります。インスタンスタイプを変更できない場合は、アップグレード前に拡張ネットワークを有効にする必要があります。
+
link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html#upgrades-in-aws-with-c4-m4-and-r4-ec2-instance-types["C4、M4、R4 EC2インスタンスタイプを使用してAWSでアップグレードする方法を確認する"^]。
link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Cloud Volumes ONTAP のEC2インスタンスタイプを変更する方法について説明します"^]。

+
を参照してください link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["ネットアップサポート"^] これらのインスタンスタイプの可用性とサポート終了の詳細については、を参照してください。





=== DS3_v2 の場合

9.9.1 リリース以降では、 DS3_v2 VM タイプは新規および既存の Cloud Volumes ONTAP システムでサポートされなくなりました。この VM タイプで既存のシステムを実行している場合は、 9.10.0 にアップグレードする前に VM タイプを変更する必要があります。
